# ==========================================
# STAGE PROFILE (Local Postgres DB)
# ==========================================
spring:
  datasource:
    # Replace the host, port, dbname, username, and password with your actual PostgreSQL credentials
    url: jdbc:postgresql://localhost:5432/caffe?prepareThreshold=0
    username: ma-78
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Use the PostgreSQL dialect instead of MySQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
