# ==========================================
# PROD PROFILE (Production Supabase DB)
# ==========================================
spring:
  datasource:
    # postgresql://postgres:[YOUR-PASSWORD]@db.nnmpklawqtadihpupmdm.supabase.co:5432/postgres
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
    username: postgres.nnmpklawqtadihpupmdm
    password: caffee@123sonya
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Use the PostgreSQL dialect instead of MySQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
