spring.application.name=caffe
#spring.datasource.url=jdbc:mysql://localhost:3306/caffe
#spring.datasource.username=root
#spring.datasource.password=root


spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:22712/railway
spring.datasource.username=root
spring.datasource.password=bKckahtLBsKCDjvECvTCHJWkazNvAOli

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#mysql://root:bKckahtLBsKCDjvECvTCHJWkazNvAOli@interchange.proxy.rlwy.net:22712/railway

cloudinary.cloud_name=dbcg3byao
cloudinary.api_key=946119375975345
cloudinary.api_secret=RtlCMUYxEHa5U5XD32PZViVd5A4